[@ww.textfield labelKey="com.midvision.rapiddeploy.bamboo.server.url" name="serverUrl" required='true'/]
[@ww.password labelKey="com.midvision.rapiddeploy.bamboo.authentication.token" name="password" required='true'/]
[@ww.textfield labelKey="com.midvision.rapiddeploy.bamboo.rapiddeployProjectName" name="rapiddeployProjectName" required='true'/]
[@ww.textfield labelKey="com.midvision.rapiddeploy.bamboo.package.name" name="packageName" required='true'/]
[@ww.textfield labelKey="com.midvision.rapiddeploy.bamboo.archive.extension" name="archiveExtension" required='true'/]
