[@ww.label labelKey="com.midvision.rapiddeploy.bamboo.server.url" name="serverUrl"/]
[@ww.label labelKey="com.midvision.rapiddeploy.bamboo.authentication.token" name="authenticationToken"/]
[@ww.label labelKey="com.midvision.rapiddeploy.bamboo.jobPlanId" name="jobPlanId"/]
[@ww.label labelKey="com.midvision.rapiddeploy.bamboo.isAsynchronous" name="isAsynchronous"/]
[@ww.label labelKey="com.midvision.rapiddeploy.bamboo.showFullLogs" name="showFullLogs"/]
