[@ww.label labelKey="com.midvision.rapiddeploy.bamboo.server.url" name="serverUrl"/]
[@ww.label labelKey="com.midvision.rapiddeploy.bamboo.authentication.token" name="authenticationToken"/]
[@ww.label labelKey="com.midvision.rapiddeploy.bamboo.rapiddeployProjectName" name="rapiddeployProjectName"/]
[@ww.label labelKey="com.midvision.rapiddeploy.bamboo.rapiddeployServerName" name="rapiddeployServerName"/]
[@ww.label labelKey="com.midvision.rapiddeploy.bamboo.rapiddeployEnvironmentName" name="rapiddeployEnvironmentName"/]
[@ww.label labelKey="com.midvision.rapiddeploy.bamboo.rapiddeployAppName" name="rapiddeployAppName"/]
[@ww.label labelKey="com.midvision.rapiddeploy.bamboo.package.name" name="packageName"/]
[@ww.label labelKey="com.midvision.rapiddeploy.bamboo.isAsynchronous" name="isAsynchronous"/]
